version: '3'

services:
  nginx:
    image: my-nginx:v1
    container_name: nginx-container
    ports:
      - "880:880"
     # 假设您的配置文件路径为 ./nginx.conf
    depends_on:
      - uwsgi
    networks:
      - web

  uwsgi:
    image: my_flask:v1  # 选择合适的 uwsgi 镜像
          #build:
    # context:.
    #  dockerfile: flask_Dockerfile
    container_name: uwsgi-container
    environment:
            #- UWSGI_HTTP=0.0.0.0:8000  
      - UWSGI_WSGI_FILE=/manager.py   # 指定你的应用   
    expose:
      - "8000"
    
    command: ["uwsgi", "--ini", "uwsgi.ini"]
    networks:
      - web
networks:
  web:
    driver: bridge
