version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "880:880"
    volumes:
      - ./flask.conf:/etc/nginx/conf.d/  # 假设您的配置文件路径为 ./nginx.conf
    depends_on:
      - uwsgi

  uwsgi:
    image: tiangolo/uwsgi-python:latest  # 选择合适的 uwsgi 镜像
    container_name: uwsgi-container
    environment:
      - UWSGI_HTTP=0.0.0.0:8000
      - UWSGI_WSGI_FILE=/manager.py   # 指定你的应用
    volumes:
      - ./:/  # 假设你的 Python 应用存放在 ./app 目录下  
