# USERNAME: "root"
# PASSWORD: "luo12138"
# HOST: "localhost"
# PORT: 3306
# DATABASE: "test"

SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:luo12138@localhost:3306/test?charset=utf8mb4'
SQLALCHEMY_TRACK_MODIFICATIONS: false
SQLALCHEMY_POOL_SIZE: 10
SQLALCHEMY_MAX_OVERFLOW: 5
SQLALCHEMY_POOL_TIMEOUT: 30
SQLALCHEMY_POOL_RECYCLE: 1800
